name: Compile Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Compiling the project
        run: |
          sudo apt-get update && apt-get upgrade 
          sudo apt-get install build-essential && apt-get install libncursesw5-dev 
          g++ *.cpp -lncursesw 
          
