name: Compile Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        run: |
          apt update && apt upgrade && apt install build-essential && apt install libncursesw5-dev && g++ *.cpp -lncursesw 
          
